### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by ChengJianjia** [Megvii-BaseDetection/DeFCN#7]
ImportError: cannot import name 'PSRoIAlign'

我的环境： pytorch1.3.2，torchvision0.4.2
请问是否是环境造成的错误?
请问源代码使用的具体环境是什么呢？

完整错误:Traceback (most recent call last):
  File "/home/cjj/cvpods/tools/train_net.py", line 28, in <module>
    from cvpods.engine import DefaultTrainer, default_argument_parser, default_setup, hooks, launch
  File "/home/cjj/cvpods/cvpods/engine/__init__.py", line 3, in <module>
    from .hooks import *
  File "/home/cjj/cvpods/cvpods/engine/hooks.py", line 16, in <module>
    from cvpods.modeling.nn_utils.precise_bn import get_bn_modules, update_bn_stats
  File "/home/cjj/cvpods/cvpods/modeling/__init__.py", line 8, in <module>
    from .meta_arch import GeneralizedRCNN, PanopticFPN, ProposalNetwork, RetinaNet, SemanticSegmentor
  File "/home/cjj/cvpods/cvpods/modeling/meta_arch/__init__.py", line 15, in <module>
    from .pointrend import CoarseMaskHead, PointRendROIHeads, PointRendSemSegHead, StandardPointHead
  File "/home/cjj/cvpods/cvpods/modeling/meta_arch/pointrend.py", line 15, in <module>
    from cvpods.modeling.roi_heads import StandardROIHeads, select_foreground_proposals
  File "/home/cjj/cvpods/cvpods/modeling/roi_heads/__init__.py", line 2, in <module>
    from .roi_heads import Res5ROIHeads, ROIHeads, StandardROIHeads, select_foreground_proposals
  File "/home/cjj/cvpods/cvpods/modeling/roi_heads/roi_heads.py", line 17, in <module>
    from ..poolers import ROIPooler
  File "/home/cjj/cvpods/cvpods/modeling/poolers.py", line 8, in <module>
    from torchvision.ops import PSRoIAlign, PSRoIPool, RoIPool
ImportError: cannot import name 'PSRoIAlign'

**Comment by wjfwzzc** [comment]
看起来是没有build，请参照[cvpods](https://github.com/Megvii-BaseDetection/cvpods)安装说明安装。
